/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
});
export const CartProduct = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([ProductId], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCart' : IDL.Func([], [IDL.Vec(CartProduct)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'removeFromCart' : IDL.Func([ProductId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const CartProduct = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  
  return IDL.Service({
    'addToCart' : IDL.Func([ProductId], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCart' : IDL.Func([], [IDL.Vec(CartProduct)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'removeFromCart' : IDL.Func([ProductId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };